[profile.default]
src = "packages/contracts/src"
test = "test"
script = "script"
out = "out"
libs = ["lib"]

solc_version = "0.8.25"

optimizer = true
optimizer_runs = 200

# Include paymasters contracts as additional sources
fs_permissions = [{ access = "read", path = "./" }, { access = "read-write", path = "./conf.json" }]
extra_output = ["abi", "evm.bytecode"]

remappings = [
    "@openzeppelin/contracts/=lib/openzeppelin-contracts/contracts/",
    "@opengsn/contracts/src/=packages/contracts/src/",
    "@uniswap/v3-periphery/=lib/v3-periphery/",
    "@uniswap/v3-core/=lib/v3-core/",
    "forge-std/=lib/forge-std/src/",
]
